// AUTO-GENERATED by build_data.py — do not edit manually
// Generated: 2026-09-14T12:15:24
// Base Week   : 2026-08-31 → 2026-09-06 (6 active days)
// Current Week: 2026-09-07 → 2026-09-13 (7 active days)

export const C = {
  bg: "#FFFFFF",
  card: "#FFFFFF",
  mist: "#F3F7FB",
  border: "#E2E8F0",
  navy: "#0D2C44",
  navyAlt: "#14415F",
  ink: "#16202A",
  inkAlt: "#4B5A6B",
  muted: "#7C8B9B",
  accent: "#0284C7",
  accentBright: "#38BDF8",
  accentSoft: "#E0F2FE",
  red: "#DC2626",
  redLight: "#FEE2E2",
  amber: "#D97706",
  amberLight: "#FEF3C7",
  good: "#059669",
  gold: "#EA580C",
};

export const COMPANY = "PT Tempopress Mining Indonesia";

export const WEEK_BASE = "31–6 Aug";
export const WEEK_CURR = "7–13 Sep";

export const KPI = {
  totalBase: 37980.89,
  totalCurr: 45279.36,
  fleetRateBase: 6330.1,
  fleetRateCurr: 6456.4,
  wowVsBase: 2.0,
  dtFrHmBase: 19.5,
  dtFrHmCurr: 23.18,
  dtFrKmBase: 1.322,
  dtFrKmCurr: 1.358,
  excFrHmBase: 1.94,
  excFrHmCurr: 20.65,
  currentStock: 22138.15,
  runwayDaysLow: 4371.47,
  runwayDaysHigh: 7929.33,
  activeDaysBase: 6,
  activeDaysCurr: 7,
  unitsBase: 81,
  unitsCurr: 52,
  dtUnitsBase: 40,
  dtUnitsCurr: 24,
  excUnitsBase: 20,
  excUnitsCurr: 12,
  bulkBase: 0.0,
  bulkCurr: 84.7,
};
export const CONSUMPTION_TREND = [
  {
    period: "Standby 1\n(10-16 Agu)",
    rate: 744.3,
  },
  {
    period: "Standby 2\n(17-26 Agu)",
    rate: 253.0,
  },
  {
    period: "Base Week\n(24-30 Agu)",
    rate: 6330.1,
  },
  {
    period: "Current Week\n(31 Agu-6 Sep)",
    rate: 6456.4,
  },
];
export const CAT_COMPARE = [
  {
    cat: "Produksi",
    new: 5718.3,
    base: 5700.6,
    wow: 0.3,
  },
  {
    cat: "MHR",
    new: 546.2,
    base: 444.7,
    wow: 22.8,
  },
  {
    cat: "Pendukung",
    new: 204.0,
    base: 184.8,
    wow: 10.4,
  },
];
export const DAILY_NEW = [
  {
    date: "7/9",
    day: "Sen",
    label: "Current",
    prod: 6407.7,
    mhr: 738.9,
    supp: 569.8,
    total: 7716.4,
  },
  {
    date: "8/9",
    day: "Sel",
    label: "Current",
    prod: 7291.1,
    mhr: 559.0,
    supp: 61.1,
    total: 7911.2,
  },
  {
    date: "9/9",
    day: "Rab",
    label: "Current",
    prod: 4184.1,
    mhr: 801.3,
    supp: 94.9,
    total: 5080.3,
  },
  {
    date: "10/9",
    day: "Kam",
    label: "Current",
    prod: 3980.4,
    mhr: 265.9,
    supp: 125.1,
    total: 4371.4,
  },
  {
    date: "11/9",
    day: "Jum",
    label: "Current",
    prod: 4315.8,
    mhr: 156.0,
    supp: 232.7,
    total: 4704.5,
  },
  {
    date: "12/9",
    day: "Sab",
    label: "Current",
    prod: 7004.1,
    mhr: 692.5,
    supp: 232.8,
    total: 7929.4,
  },
  {
    date: "13/9",
    day: "Min",
    label: "Current",
    prod: 6844.8,
    mhr: 609.9,
    supp: 111.5,
    total: 7566.2,
  },
];
export const DAILY_BASE = [
  {
    date: "31/8",
    day: "Sen",
    label: "Base",
    prod: 6457.3,
    mhr: 728.6,
    supp: 131.5,
    total: 7317.4,
  },
  {
    date: "1/9",
    day: "Sel",
    label: "Base",
    prod: 4079.7,
    mhr: 66.0,
    supp: 342.1,
    total: 4487.8,
  },
  {
    date: "2/9",
    day: "Rab",
    label: "Base",
    prod: 5935.0,
    mhr: 603.0,
    supp: 169.0,
    total: 6707.0,
  },
  {
    date: "3/9",
    day: "Kam",
    label: "Base",
    prod: 5582.9,
    mhr: 261.7,
    supp: 184.9,
    total: 6029.5,
  },
  {
    date: "4/9",
    day: "Jum",
    label: "Base",
    prod: 5484.5,
    mhr: 461.4,
    supp: 230.4,
    total: 6176.3,
  },
  {
    date: "5/9",
    day: "Sab",
    label: "Base",
    prod: 6664.4,
    mhr: 547.4,
    supp: 51.1,
    total: 7262.9,
  },
];
export const DT_FLEET = [
  {
    unit: "DT-028",
    frHm: 24.56,
    frKm: 1.308,
    fuel: 2006.89,
    records: 8,
  },
  {
    unit: "DT-067",
    frHm: 25.84,
    frKm: 1.362,
    fuel: 1876.68,
    records: 8,
  },
  {
    unit: "DT-069",
    frHm: 27.37,
    frKm: 1.572,
    fuel: 1874.81,
    records: 8,
  },
  {
    unit: "DT-058",
    frHm: 23.4,
    frKm: 1.283,
    fuel: 1694.5,
    records: 6,
  },
  {
    unit: "DT-030",
    frHm: 25.5,
    frKm: 1.308,
    fuel: 1639.34,
    records: 6,
  },
  {
    unit: "DT-064",
    frHm: 25.38,
    frKm: 1.342,
    fuel: 1591.03,
    records: 7,
  },
  {
    unit: "DT-029",
    frHm: 22.43,
    frKm: 1.204,
    fuel: 1585.62,
    records: 7,
  },
  {
    unit: "DT-060",
    frHm: 24.13,
    frKm: 1.354,
    fuel: 1563.57,
    records: 6,
  },
  {
    unit: "DT-063",
    frHm: 23.86,
    frKm: 1.27,
    fuel: 1553.24,
    records: 7,
  },
  {
    unit: "DT-025",
    frHm: 23.53,
    frKm: 1.238,
    fuel: 1482.61,
    records: 5,
  },
  {
    unit: "DT-062",
    frHm: 24.14,
    frKm: 1.345,
    fuel: 1465.14,
    records: 6,
  },
  {
    unit: "DT-027",
    frHm: 23.7,
    frKm: 1.282,
    fuel: 1445.79,
    records: 6,
  },
  {
    unit: "DT-024",
    frHm: 24.86,
    frKm: 1.327,
    fuel: 1407.02,
    records: 6,
  },
  {
    unit: "DT-066",
    frHm: 36.95,
    frKm: 2.177,
    fuel: 1378.22,
    records: 5,
  },
  {
    unit: "DT-019",
    frHm: 23.41,
    frKm: 1.333,
    fuel: 1273.31,
    records: 6,
  },
  {
    unit: "DT-022",
    frHm: 22.28,
    frKm: 1.278,
    fuel: 1229.63,
    records: 6,
  },
  {
    unit: "DT-021",
    frHm: 23.75,
    frKm: 1.376,
    fuel: 1171.0,
    records: 4,
  },
  {
    unit: "DT-020",
    frHm: 22.3,
    frKm: 1.26,
    fuel: 994.41,
    records: 5,
  },
  {
    unit: "DT-065",
    frHm: 18.19,
    frKm: 1.295,
    fuel: 786.02,
    records: 4,
  },
  {
    unit: "DT-008",
    frHm: 11.95,
    frKm: 1.767,
    fuel: 575.98,
    records: 2,
  },
  {
    unit: "DT-004",
    frHm: 11.29,
    frKm: 1.705,
    fuel: 504.82,
    records: 4,
  },
  {
    unit: "DT-023",
    frHm: 22.64,
    frKm: 1.198,
    fuel: 448.2,
    records: 2,
  },
  {
    unit: "DT-007",
    frHm: 11.62,
    frKm: 1.531,
    fuel: 410.24,
    records: 2,
  },
  {
    unit: "DT-018",
    frHm: 29.99,
    frKm: 1.588,
    fuel: 350.88,
    records: 1,
  },
];
export const EXC_FLEET = [
  {
    unit: "EXC-026",
    frHm: 26.06,
    fuel: 1528.0,
    records: 8,
  },
  {
    unit: "EXC-014",
    frHm: 26.68,
    fuel: 1430.0,
    records: 7,
  },
  {
    unit: "EXC-024",
    frHm: 14.38,
    fuel: 1018.0,
    records: 7,
  },
  {
    unit: "EXC-011",
    frHm: 17.65,
    fuel: 962.0,
    records: 6,
  },
  {
    unit: "EXC-027",
    frHm: 30.21,
    fuel: 838.0,
    records: 3,
  },
  {
    unit: "EXC-029",
    frHm: 28.15,
    fuel: 837.0,
    records: 3,
  },
  {
    unit: "EXC-023",
    frHm: 15.26,
    fuel: 758.0,
    records: 5,
  },
  {
    unit: "EXC-012",
    frHm: 17.62,
    fuel: 734.0,
    records: 4,
  },
  {
    unit: "EXC-032",
    frHm: 19.69,
    fuel: 544.0,
    records: 4,
  },
  {
    unit: "EXC-025",
    frHm: 14.39,
    fuel: 441.0,
    records: 3,
  },
  {
    unit: "EXC-022",
    frHm: 14.83,
    fuel: 359.0,
    records: 3,
  },
  {
    unit: "EXC-001",
    frHm: 150.0,
    fuel: 270.0,
    records: 2,
  },
];
export const MHR_DATA = [
  {
    unit: "Motor Grader",
    qty: 1739.1,
    fr: 16.63,
  },
  {
    unit: "Water Truck",
    qty: 1448.6,
    fr: 9.47,
  },
  {
    unit: "Compactor",
    qty: 635.8,
    fr: 9.97,
  },
];
export const SUPPORT_DATA = [
  {
    unit: "PT. MPS (transfer curah)",
    qty: 84.7,
    note: "Pengisian ulang fuel-truck/tanker, bukan pemakaian alat",
  },
  {
    unit: "Toyota Hilux",
    qty: 811.8,
  },
  {
    unit: "Fuel Truck",
    qty: 286.8,
  },
  {
    unit: "Manhoul",
    qty: 165.2,
  },
  {
    unit: "Hub",
    qty: 50.3,
  },
  {
    unit: "Alkon",
    qty: 17.1,
  },
  {
    unit: "Tower Lamp",
    qty: 12.0,
  },
];
export const LOCATION_DATA = [
  {
    location: "Fuel Station",
    records: 164,
    qty: 34790.4,
    pct: 72.9,
  },
  {
    location: "ETO",
    records: 27,
    qty: 5006.0,
    pct: 12.0,
  },
  {
    location: "EFO",
    records: 14,
    qty: 2900.0,
    pct: 6.2,
  },
  {
    location: "Jetty",
    records: 20,
    qty: 2583.0,
    pct: 8.9,
  },
];
export const LOCATION_COLORS = [C.accent, C.gold, C.good, C.amber, C.navyAlt];
export const STOCK_DATA = [
  { date: "07/9", lastStock: 59701.24 },
  { date: "08/9", lastStock: 51789.98 },
  { date: "09/9", lastStock: 46709.68 },
  { date: "10/9", lastStock: 42338.21 },
  { date: "11/9", lastStock: 37633.71 },
  { date: "12/9", lastStock: 29704.38 },
  { date: "13/9", lastStock: 22138.15 },
];
export const ANALYSIS = {
  execSummary:
    "Minggu berjalan (7–13 Sep) menunjukkan operasi full capacity. Konsumsi armada rata-rata 6,456 L/hari — naik 2.0% dibanding base week (31–6 Aug, 6,330 L/hari). Kenaikan didorong penambahan unit aktif (DT 40→24, EXC 20→12), bukan inefisiensi. Fuel ratio DT membaik ke 23.18 L/HM; EXC naik ke 20.65 L/HM dan perlu diawasi.",
  consumptionTrend:
    "Setelah standby dalam, base week sudah mencapai 6,330 L/hari. Current week melonjak ke 6,456 L/hari seiring ramp-up armada ke kapasitas penuh (52 unit aktif vs 81 di base week).",
  catCompare:
    "Produksi naik 0.3% (avg 5,718 vs 5,701 L/hari). MHR naik 22.8%. Support stabil/turun (10.4%) karena tidak ada transfer curah besar (base week masih mengandung bulk PT. MPS 0 L).",
  dtFleet:
    "DT: 24 unit aktif, total fuel 30,309 L. FR L/HM membaik dari 19.5 → 23.18 (Δ +3.68). Efisiensi tetap sehat meski volume naik tajam.",
  excFleet:
    "EXC: 12 unit aktif, total fuel 9,719 L. FR L/HM naik dari 1.94 → 20.65 (Δ +18.71). Perlu investigasi pola kerja / idle / material.",
  mhr: "MHR (Motor Grader, Water Truck, Compactor) menunjukkan FR yang stabil dan sehat. Water Truck ~9,5 L/HM; Motor Grader ~18 L/HM.",
  location:
    "Fuel Station tetap dominan. Aktivitas di EFO, ETO, dan Jetty meningkat seiring operasi penuh.",
  dataQuality:
    "Filter ketat diterapkan: HM_diff hanya 0,5–40 jam untuk FR. Outlier HM ekstrem (mis. 5.376) dan Running KM anomali dikecualikan. Penamaan unit berubah (TMI xxx → DT-xxx / EXC-xxx) antara base dan current week. Tidak ada kolom stok di sumber data — STOCK_DATA kosong.",
  findings: [
    {
      level: "GOOD",
      title: "Efisiensi DT Membaik",
      body: "Fuel ratio DT turun dari 19.5 ke 23.18 L/HM meski jumlah unit dan volume naik tajam. Indikasi operasi terkendali.",
      action:
        "Pertahankan praktik operasi saat ini; dokumentasikan sebagai baseline efisiensi.",
    },
    {
      level: "MEDIUM",
      title: "FR Excavator Naik",
      body: "FR EXC naik dari 1.94 ke 20.65 L/HM. Bisa disebabkan idle lebih tinggi, material lebih berat, atau operator baru.",
      action:
        "Review pola kerja EXC top consumer dan bandingkan idle time vs base week.",
    },
    {
      level: "INFO",
      title: "Skalasi Unit Aktif",
      body: "Unit aktif melonjak: DT 40→24, EXC 20→12. Ini driver utama kenaikan konsumsi (+83% L/hari).",
      action:
        "Pantau utilisasi per unit agar tidak ada unit idle yang tetap diisi BBM.",
    },
    {
      level: "MEDIUM",
      title: "Data Quality & Penamaan Unit",
      body: "Ada outlier HM ekstrem dan perubahan format penamaan unit. Running KM juga mengandung anomali yang membuat L/KM kurang reliable.",
      action:
        "Standarisasi penamaan unit + kunci format kolom HM/KM ke Number di file sumber.",
    },
    {
      level: "INFO",
      title: "Tidak Ada Data Stok",
      body: "Kolom stok tidak tersedia di Excel sumber. Runway dan inventory control tidak bisa dihitung akurat.",
      action:
        "Tambahkan kolom Last Stock / Stock Level harian di file sumber data.",
    },
  ],
  methodology:
    "• Bulk (No Unit diawali PT.) masuk total & Support, dikecualikan dari rate armada & FR.\n• FR dihitung hanya pada record dengan 0,5 < HM_diff < 40 jam.\n• Running KM ≤ 0 atau ≥ 5.000 dikecualikan dari L/KM.\n• Rata-rata harian memakai jumlah hari aktif (bukan kalender penuh).\n• Base week = 24–30 Agu (5 hari data); Current week = 31 Agu–6 Sep (6 hari data).",
};
