// AUTO-GENERATED by build_data.py — do not edit manually
export const WEEK_NEW = "31 Aug–5 Sep";
export const WEEK_BASELINE = "24–30 Aug";

export const KPI = {
  "totalNew": 37980.9,
  "dailyNew": 6330.2,
  "dailyBaseline": 2465.4,
  "wow": 156.8,
  "dtFrHmNew": 19.5,
  "dtFrHmBase": 22.2,
  "dtFrKmNew": 0.211,
  "dtFrKmBase": 1.235
};
export const SLOPE_CONSUMPTION = [
  {
    "x": "Baseline",
    "v": 2465.4
  },
  {
    "x": "This Week",
    "v": 6330.2
  }
];
export const SLOPE_FR_HM = [
  {
    "x": "Baseline",
    "v": 22.2
  },
  {
    "x": "This Week",
    "v": 19.5
  }
];
export const SLOPE_FR_KM = [
  {
    "x": "Baseline",
    "v": 1.235
  },
  {
    "x": "This Week",
    "v": 0.211
  }
];
export const CAT_COMPARE = [
  {
    "cat": "Production",
    "new": 5700.6,
    "base": 2040.2,
    "wow": 179.4
  },
  {
    "cat": "MHR",
    "new": 263.9,
    "base": 192.2,
    "wow": 37.3
  },
  {
    "cat": "Support",
    "new": 365.6,
    "base": 232.9,
    "wow": 57.0
  }
];
export const DAILY_NEW = [
  {
    "date": "31/8",
    "day": "Mon",
    "prod": 6457.3,
    "mhr": 491.9,
    "supp": 368.2,
    "total": 7317.3
  },
  {
    "date": "1/9",
    "day": "Tue",
    "prod": 4079.7,
    "mhr": 66.0,
    "supp": 342.1,
    "total": 4487.7
  },
  {
    "date": "2/9",
    "day": "Wed",
    "prod": 5935.0,
    "mhr": 216.3,
    "supp": 555.8,
    "total": 6707.1
  },
  {
    "date": "3/9",
    "day": "Thu",
    "prod": 5582.9,
    "mhr": 261.7,
    "supp": 184.9,
    "total": 6029.5
  },
  {
    "date": "4/9",
    "day": "Fri",
    "prod": 5484.5,
    "mhr": 0.0,
    "supp": 691.8,
    "total": 6176.3
  },
  {
    "date": "5/9",
    "day": "Sat",
    "prod": 6664.4,
    "mhr": 547.4,
    "supp": 51.1,
    "total": 7262.9
  }
];
export const DT_FLEET = [
  {
    "unit": "DT-019",
    "frHm": 22.36,
    "frKm": 1.377,
    "fuel": 1061.9,
    "records": 5
  },
  {
    "unit": "DT-063",
    "frHm": 27.56,
    "frKm": 1.387,
    "fuel": 1055.7,
    "records": 4
  },
  {
    "unit": "DT-030",
    "frHm": 23.38,
    "frKm": 1.248,
    "fuel": 1019.58,
    "records": 4
  },
  {
    "unit": "DT-024",
    "frHm": 24.43,
    "frKm": 1.267,
    "fuel": 1016.29,
    "records": 5
  },
  {
    "unit": "DT-020",
    "frHm": 21.29,
    "frKm": 1.29,
    "fuel": 994.34,
    "records": 4
  },
  {
    "unit": "DT-062",
    "frHm": 22.16,
    "frKm": 1.276,
    "fuel": 983.95,
    "records": 4
  },
  {
    "unit": "DT-023",
    "frHm": 21.79,
    "frKm": 1.207,
    "fuel": 971.99,
    "records": 4
  },
  {
    "unit": "DT-064",
    "frHm": 24.18,
    "frKm": 1.286,
    "fuel": 928.66,
    "records": 4
  },
  {
    "unit": "DT-027",
    "frHm": 20.16,
    "frKm": 1.238,
    "fuel": 884.84,
    "records": 4
  },
  {
    "unit": "DT-060",
    "frHm": 24.41,
    "frKm": 1.378,
    "fuel": 876.28,
    "records": 3
  },
  {
    "unit": "DT-029",
    "frHm": 25.94,
    "frKm": 1.311,
    "fuel": 858.56,
    "records": 4
  },
  {
    "unit": "DT-025",
    "frHm": 21.77,
    "frKm": 1.229,
    "fuel": 781.43,
    "records": 4
  },
  {
    "unit": "DT-028",
    "frHm": 23.36,
    "frKm": 1.363,
    "fuel": 759.21,
    "records": 3
  },
  {
    "unit": "DT-004",
    "frHm": 11.92,
    "frKm": 1.844,
    "fuel": 715.36,
    "records": 3
  },
  {
    "unit": "DT-065",
    "frHm": 20.73,
    "frKm": 1.328,
    "fuel": 631.24,
    "records": 2
  },
  {
    "unit": "DT-011",
    "frHm": 12.09,
    "frKm": 1.719,
    "fuel": 603.35,
    "records": 3
  },
  {
    "unit": "DT-021",
    "frHm": 19.38,
    "frKm": 1.408,
    "fuel": 587.28,
    "records": 2
  },
  {
    "unit": "DT-058",
    "frHm": 18.73,
    "frKm": 1.132,
    "fuel": 575.06,
    "records": 3
  },
  {
    "unit": "DT-007",
    "frHm": 11.26,
    "frKm": 1.472,
    "fuel": 565.34,
    "records": 3
  },
  {
    "unit": "DT-022",
    "frHm": 20.27,
    "frKm": 1.448,
    "fuel": 563.4,
    "records": 2
  },
  {
    "unit": "DT-008",
    "frHm": 11.6,
    "frKm": 1.821,
    "fuel": 431.46,
    "records": 2
  },
  {
    "unit": "TMI 064 DT",
    "frHm": 25.79,
    "frKm": 1.314,
    "fuel": 345.55,
    "records": 1
  },
  {
    "unit": "DT-017",
    "frHm": 11.35,
    "frKm": 0,
    "fuel": 330.19,
    "records": 1
  },
  {
    "unit": "TMI 063 DT",
    "frHm": 25.75,
    "frKm": 1.391,
    "fuel": 329.66,
    "records": 1
  },
  {
    "unit": "TMI 028 DT",
    "frHm": 25.62,
    "frKm": 1.345,
    "fuel": 325.41,
    "records": 1
  },
  {
    "unit": "TMI 019 DT",
    "frHm": 22.31,
    "frKm": 1.354,
    "fuel": 316.82,
    "records": 1
  },
  {
    "unit": "TMI 062 DT",
    "frHm": 25.38,
    "frKm": 1.301,
    "fuel": 312.16,
    "records": 1
  },
  {
    "unit": "TMI 020 DT",
    "frHm": 26.0,
    "frKm": 1.322,
    "fuel": 312.06,
    "records": 1
  },
  {
    "unit": "TMI 060 DT",
    "frHm": 24.58,
    "frKm": 1.398,
    "fuel": 304.82,
    "records": 1
  },
  {
    "unit": "TMI 030 DT",
    "frHm": 22.35,
    "frKm": 1.252,
    "fuel": 301.75,
    "records": 1
  },
  {
    "unit": "DT-015",
    "frHm": 27.0,
    "frKm": 1.856,
    "fuel": 297.0,
    "records": 1
  },
  {
    "unit": "TMI 027 DT",
    "frHm": 22.67,
    "frKm": 1.218,
    "fuel": 294.67,
    "records": 1
  },
  {
    "unit": "TMI 029 DT",
    "frHm": 26.83,
    "frKm": 1.267,
    "fuel": 273.7,
    "records": 1
  },
  {
    "unit": "TMI 058 DT",
    "frHm": 25.32,
    "frKm": 1.432,
    "fuel": 273.47,
    "records": 1
  },
  {
    "unit": "TMI 023 DT",
    "frHm": 24.43,
    "frKm": 1.233,
    "fuel": 266.26,
    "records": 1
  },
  {
    "unit": "TMI 025 DT",
    "frHm": 23.96,
    "frKm": 1.215,
    "fuel": 263.56,
    "records": 1
  },
  {
    "unit": "DT-010",
    "frHm": 3.96,
    "frKm": 0.655,
    "fuel": 237.05,
    "records": 1
  },
  {
    "unit": "TMI 021 DT",
    "frHm": 20.31,
    "frKm": 1.237,
    "fuel": 221.38,
    "records": 1
  },
  {
    "unit": "DT-001",
    "frHm": 0,
    "frKm": 0.002,
    "fuel": 202.54,
    "records": 1
  },
  {
    "unit": "DT-044",
    "frHm": 10.13,
    "frKm": 1.02,
    "fuel": 155.0,
    "records": 1
  }
];
export const FLEET_TREND = [
  {
    "d": "31/8",
    "dt": 14,
    "exc": 8
  },
  {
    "d": "1/9",
    "dt": 13,
    "exc": 5
  },
  {
    "d": "2/9",
    "dt": 15,
    "exc": 10
  },
  {
    "d": "3/9",
    "dt": 14,
    "exc": 8
  },
  {
    "d": "4/9",
    "dt": 15,
    "exc": 10
  },
  {
    "d": "5/9",
    "dt": 19,
    "exc": 10
  }
];
export const EQUIPMENT_LEADERBOARD = [
  {
    "name": "Water Truck",
    "cat": "Support",
    "qty": 1084.9
  },
  {
    "name": "Motor Grader",
    "cat": "MHR",
    "qty": 856.0
  },
  {
    "name": "Compactor",
    "cat": "MHR",
    "qty": 727.4
  },
  {
    "name": "Toyota Hilux",
    "cat": "Support",
    "qty": 525.2
  },
  {
    "name": "Genset",
    "cat": "Support",
    "qty": 450.0
  },
  {
    "name": "Tower Lamp",
    "cat": "Support",
    "qty": 53.0
  },
  {
    "name": "Alkon",
    "cat": "Support",
    "qty": 6.4
  }
];
export const LOGGING_TREND = [
  {
    "date": "01/07",
    "records": 28
  },
  {
    "date": "02/07",
    "records": 29
  },
  {
    "date": "03/07",
    "records": 31
  },
  {
    "date": "04/07",
    "records": 26
  },
  {
    "date": "05/07",
    "records": 6
  },
  {
    "date": "06/07",
    "records": 28
  },
  {
    "date": "07/07",
    "records": 26
  },
  {
    "date": "08/07",
    "records": 29
  },
  {
    "date": "09/07",
    "records": 27
  },
  {
    "date": "10/07",
    "records": 36
  },
  {
    "date": "11/07",
    "records": 24
  },
  {
    "date": "12/07",
    "records": 2
  },
  {
    "date": "13/07",
    "records": 24
  },
  {
    "date": "14/07",
    "records": 27
  },
  {
    "date": "15/07",
    "records": 24
  },
  {
    "date": "16/07",
    "records": 1
  },
  {
    "date": "17/07",
    "records": 2
  },
  {
    "date": "18/07",
    "records": 2
  },
  {
    "date": "20/07",
    "records": 2
  },
  {
    "date": "22/07",
    "records": 2
  },
  {
    "date": "24/07",
    "records": 2
  },
  {
    "date": "25/07",
    "records": 25
  },
  {
    "date": "26/07",
    "records": 1
  },
  {
    "date": "27/07",
    "records": 36
  },
  {
    "date": "28/07",
    "records": 25
  },
  {
    "date": "29/07",
    "records": 31
  },
  {
    "date": "30/07",
    "records": 33
  },
  {
    "date": "31/07",
    "records": 33
  },
  {
    "date": "01/08",
    "records": 25
  },
  {
    "date": "02/08",
    "records": 27
  },
  {
    "date": "03/08",
    "records": 28
  },
  {
    "date": "04/08",
    "records": 24
  },
  {
    "date": "05/08",
    "records": 24
  },
  {
    "date": "06/08",
    "records": 25
  },
  {
    "date": "07/08",
    "records": 13
  },
  {
    "date": "08/08",
    "records": 24
  },
  {
    "date": "10/08",
    "records": 4
  },
  {
    "date": "11/08",
    "records": 14
  },
  {
    "date": "12/08",
    "records": 2
  },
  {
    "date": "13/08",
    "records": 2
  },
  {
    "date": "14/08",
    "records": 4
  },
  {
    "date": "15/08",
    "records": 4
  },
  {
    "date": "17/08",
    "records": 2
  },
  {
    "date": "18/08",
    "records": 2
  },
  {
    "date": "19/08",
    "records": 1
  },
  {
    "date": "20/08",
    "records": 2
  },
  {
    "date": "21/08",
    "records": 2
  },
  {
    "date": "23/08",
    "records": 2
  },
  {
    "date": "24/08",
    "records": 3
  },
  {
    "date": "27/08",
    "records": 14
  },
  {
    "date": "28/08",
    "records": 21
  },
  {
    "date": "29/08",
    "records": 25
  },
  {
    "date": "30/08",
    "records": 16
  },
  {
    "date": "31/08",
    "records": 28
  },
  {
    "date": "01/09",
    "records": 22
  },
  {
    "date": "02/09",
    "records": 32
  },
  {
    "date": "03/09",
    "records": 27
  },
  {
    "date": "04/09",
    "records": 29
  },
  {
    "date": "05/09",
    "records": 33
  }
];
export const LOCATION_DATA = [
  {
    "location": "Fuel Station",
    "records": 114,
    "qty": 25733.9,
    "avgLead": 4.3,
    "pct": 66.7
  },
  {
    "location": "EFO",
    "records": 25,
    "qty": 5659.0,
    "avgLead": 3.3,
    "pct": 14.6
  },
  {
    "location": "ETO",
    "records": 13,
    "qty": 3223.0,
    "avgLead": 2.8,
    "pct": 7.6
  },
  {
    "location": "Jetty",
    "records": 15,
    "qty": 2862.0,
    "avgLead": 1.9,
    "pct": 8.8
  },
  {
    "location": "Mess TMI",
    "records": 4,
    "qty": 503.0,
    "avgLead": 6.8,
    "pct": 2.3
  }
];
